// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Boat.proto

package com.lorenzo.boat.api;

public final class BoatProtos {
  private BoatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lorenzo_boat_api_Boat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lorenzo_boat_api_Boat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SpaceShipProtos.proto\022\024com.lorenzo.boa" +
      "t.api\"\216\001\n\004Boat\022\r\n\005model\030\001 \001(\t\022\017\n\007captain" +
      "\030\002 \001(\t\022\014\n\004fuel\030\003 \001(\005\0223\n\005cargo\030\004 \001(\0162$.co" +
      "m.lorenzo.boat.api.Boat.CargoType\"#\n\tCar" +
      "goType\022\t\n\005FRUIT\020\000\022\013\n\007WEAPONS\020\001B$\n\024com.lo" +
      "renzo.boat.apiB\nBoatProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lorenzo_boat_api_Boat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lorenzo_boat_api_Boat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lorenzo_boat_api_Boat_descriptor,
        new java.lang.String[] { "Model", "Captain", "Fuel", "Cargo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
