// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Boat.proto

package com.lorenzo.boat.api;

public interface BoatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lorenzo.api.Boat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model = 1;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 1;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string captain = 2;</code>
   */
  java.lang.String getCaptain();
  /**
   * <code>string captain = 2;</code>
   */
  com.google.protobuf.ByteString
      getCaptainBytes();

  /**
   * <code>int32 fuel = 3;</code>
   */
  int getFuel();

  /**
   * <code>.com.lorenzo.api.Boat.CargoType cargo = 4;</code>
   */
  int getCargoValue();
  /**
   * <code>.com.lorenzo.api.Boat.CargoType cargo = 4;</code>
   */
  Boat.CargoType getCargo();
}
